source "https://rubygems.org"

gem 'bson', '~> 4.2', '>= 4.2.1'
gem 'capybara'
gem 'cucumber'
gem 'mongo'
gem 'rspec'
gem 'selenium-webdriver'
gem 'rubysl-mkmf', '~> 2.1'
gem 'build-makefile', '~> 1.0', '>= 1.0.1'